#!/usr/bin/env node

"use strict";

var request = require('request');

function isLinuxSupported(appid) {
  request({
    url: "http://store.steampowered.com/api/appdetails",
    qs: {"appids": appid}
  }, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      var completeData = JSON.parse(body);
      var data = completeData[Object.keys(completeData)[0]].data;
      if (data.platforms.linux === true) {
        console.log(data.name + " now supports Linux");
      }
    } else {
      console.log(error);
      console.log(response.statusCode);
      console.log(body);
    }
  });
}

function usage() {
  console.error("./checker appid");
  console.error("Example: ./checker 255220");
}

(function() {
  var index = 2, appid;
  if (process.argv.length <= 2) {
    usage();
    process.exit();
  }
  while (index < process.argv.length) {
    if (process.argv[index] == "--help") {
      usage();
      process.exit();
    } else {
      appid = parseInt(process.argv[index]);
    }
    index++;
  }

  if (isNaN(appid)) {
    console.error("Appid must be an integer.");
    process.exit();
  }
  isLinuxSupported(appid);
})();
